apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: montandon-eoapi

resources:
  - montandon-eoapi-spc.yaml

configMapGenerator:
  - name: stac-auth-proxy-filters
    files:
      - montandon_filters.py=stac-auth-proxy/montandon_filters.py
